/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./RedSVD.i



#define SWIG_VERSION 0x040301
#define SWIGGO
#define SWIGMODULE redsvd
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include <typeinfo>
#include <stdexcept>


#include <map>
#include <algorithm>
#include <stdexcept>


#include "RedSVD.h"

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_redsvd_578cfac526a98b63(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_redsvd_578cfac526a98b63(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_delete_Wrapped_GoRedSVD_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  
  delete arg1;
  
}


GoRedSVD *_wrap_new_Wrapped_GoRedSVD_redsvd_578cfac526a98b63() {
  GoRedSVD *result = 0 ;
  GoRedSVD *_swig_go_result;
  
  
  result = (GoRedSVD *)new GoRedSVD();
  *(GoRedSVD **)&_swig_go_result = (GoRedSVD *)result; 
  return _swig_go_result;
}


_goslice_ _wrap_Wrapped_GoRedSVD_matrixU_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  MatrixXf result;
  _goslice_ _swig_go_result;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  
  result = (arg1)->matrixU();
  
  {
    _goslice_ *a;
    _swig_go_result.array = malloc(sizeof(_goslice_) * (&result)->rows());
    for (int i = 0, nRows = (&result)->rows(), nCols = (&result)->cols(); i < nRows; ++i) {
      _goslice_ *row = &((_goslice_ *)_swig_go_result.array)[i];
      row->array = malloc(sizeof(float) * nCols);
      row->len = nCols;
      row->cap = nCols;
      for (int j = 0; j < nCols; ++j) {
        ((float *)row->array)[j] = result(i, j);
      }
    }
    _swig_go_result.len = (&result)->rows();
    _swig_go_result.cap = _swig_go_result.len;
  }
  
  return _swig_go_result;
}


_goslice_ _wrap_Wrapped_GoRedSVD_matrixUNotNormalized_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  MatrixXf result;
  _goslice_ _swig_go_result;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  
  result = (arg1)->matrixUNotNormalized();
  
  {
    _goslice_ *a;
    _swig_go_result.array = malloc(sizeof(_goslice_) * (&result)->rows());
    for (int i = 0, nRows = (&result)->rows(), nCols = (&result)->cols(); i < nRows; ++i) {
      _goslice_ *row = &((_goslice_ *)_swig_go_result.array)[i];
      row->array = malloc(sizeof(float) * nCols);
      row->len = nCols;
      row->cap = nCols;
      for (int j = 0; j < nCols; ++j) {
        ((float *)row->array)[j] = result(i, j);
      }
    }
    _swig_go_result.len = (&result)->rows();
    _swig_go_result.cap = _swig_go_result.len;
  }
  
  return _swig_go_result;
}


_goslice_ _wrap_Wrapped_GoRedSVD_singularValues_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  ScalarXf result;
  _goslice_ _swig_go_result;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  
  result = (arg1)->singularValues();
  
  {
    _swig_go_result.array = malloc((&result)->rows() * (&result)->cols() * sizeof(float));
    _swig_go_result.len = (&result)->rows() * (&result)->cols();
    _swig_go_result.cap = (&result)->rows() * (&result)->cols();
    memcpy(_swig_go_result.array, &result(0), (&result)->rows() * (&result)->cols() * sizeof(float));
  }
  
  return _swig_go_result;
}


_goslice_ _wrap_Wrapped_GoRedSVD_matrixV_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  MatrixXf result;
  _goslice_ _swig_go_result;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  
  result = (arg1)->matrixV();
  
  {
    _goslice_ *a;
    _swig_go_result.array = malloc(sizeof(_goslice_) * (&result)->rows());
    for (int i = 0, nRows = (&result)->rows(), nCols = (&result)->cols(); i < nRows; ++i) {
      _goslice_ *row = &((_goslice_ *)_swig_go_result.array)[i];
      row->array = malloc(sizeof(float) * nCols);
      row->len = nCols;
      row->cap = nCols;
      for (int j = 0; j < nCols; ++j) {
        ((float *)row->array)[j] = result(i, j);
      }
    }
    _swig_go_result.len = (&result)->rows();
    _swig_go_result.cap = _swig_go_result.len;
  }
  
  return _swig_go_result;
}


_goslice_ _wrap_Wrapped_GoRedSVD_matrixVNotNormalized_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  MatrixXf result;
  _goslice_ _swig_go_result;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  
  result = (arg1)->matrixVNotNormalized();
  
  {
    _goslice_ *a;
    _swig_go_result.array = malloc(sizeof(_goslice_) * (&result)->rows());
    for (int i = 0, nRows = (&result)->rows(), nCols = (&result)->cols(); i < nRows; ++i) {
      _goslice_ *row = &((_goslice_ *)_swig_go_result.array)[i];
      row->array = malloc(sizeof(float) * nCols);
      row->len = nCols;
      row->cap = nCols;
      for (int j = 0; j < nCols; ++j) {
        ((float *)row->array)[j] = result(i, j);
      }
    }
    _swig_go_result.len = (&result)->rows();
    _swig_go_result.cap = _swig_go_result.len;
  }
  
  return _swig_go_result;
}


void _wrap_Wrapped_GoRedSVD_setUnnormalized_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0, bool _swig_go_1) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  bool arg2 ;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  (arg1)->setUnnormalized(arg2);
  
}


bool _wrap_Wrapped_GoRedSVD_redSVD__SWIG_0_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  
  result = (bool)(arg1)->redSVD();
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_Wrapped_GoRedSVD_redSVD__SWIG_1_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0, intgo _swig_go_1) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  int arg2 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (bool)(arg1)->redSVD(arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_Wrapped_GoRedSVD_setDenseMatrix32_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0, _goslice_ _swig_go_1) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  int arg2 ;
  int arg3 ;
  float **arg4 = (float **) 0 ;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  
  {
    float *tmp;
    int maxlen = 0;
    
    for (int i = 0; i < _swig_go_1.len; i++) {
      _goslice_ *row = &((_goslice_ *)_swig_go_1.array)[i];
      if (row->len > maxlen) maxlen = row->len;
    }
    
    tmp = (float * )malloc(sizeof(float) * _swig_go_1.len * maxlen);
    for (int i = 0; i < _swig_go_1.len; i++) {
      _goslice_ *row = &((_goslice_ *)_swig_go_1.array)[i];
      memcpy((void *)(tmp + (maxlen * i)), (float *)row->array, row->len * sizeof(float));
    }
    
    arg2 = _swig_go_1.len;
    arg3 = maxlen;
    arg4 = &tmp;
  }
  
  
  (arg1)->setDenseMatrix32(arg2,arg3,arg4);
  
}


void _wrap_Wrapped_GoRedSVD_initializeSparseMatrix_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  (arg1)->initializeSparseMatrix(arg2,arg3);
  
}


void _wrap_Wrapped_GoRedSVD_finalizeSparseMatrix_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  
  (arg1)->finalizeSparseMatrix();
  
}


bool _wrap_Wrapped_GoRedSVD_addSparseMatrixRow_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, _goslice_ _swig_go_3) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  int arg2 ;
  int arg3 ;
  float *arg4 = (float *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = *(float **)&_swig_go_3; 
  
  result = (bool)(arg1)->addSparseMatrixRow(arg2,arg3,(float const *)arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


_goslice_ _wrap_Wrapped_GoRedSVD_getColumnNorms_redsvd_578cfac526a98b63(GoRedSVD *_swig_go_0) {
  GoRedSVD *arg1 = (GoRedSVD *) 0 ;
  ScalarXf result;
  _goslice_ _swig_go_result;
  
  arg1 = *(GoRedSVD **)&_swig_go_0; 
  
  result = (arg1)->getColumnNorms();
  
  {
    _swig_go_result.array = malloc((&result)->rows() * (&result)->cols() * sizeof(float));
    _swig_go_result.len = (&result)->rows() * (&result)->cols();
    _swig_go_result.cap = (&result)->rows() * (&result)->cols();
    memcpy(_swig_go_result.array, &result(0), (&result)->rows() * (&result)->cols() * sizeof(float));
  }
  
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

