/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./RedSVD.i

package redsvd

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _goslice_ swig_type_1;
typedef _goslice_ swig_type_2;
typedef _goslice_ swig_type_3;
typedef _goslice_ swig_type_4;
typedef _goslice_ swig_type_5;
typedef _goslice_ swig_type_6;
typedef _goslice_ swig_type_7;
typedef _goslice_ swig_type_8;
extern void _wrap_Swig_free_redsvd_578cfac526a98b63(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_redsvd_578cfac526a98b63(swig_intgo arg1);
extern void _wrap_delete_Wrapped_GoRedSVD_redsvd_578cfac526a98b63(uintptr_t arg1);
extern uintptr_t _wrap_new_Wrapped_GoRedSVD_redsvd_578cfac526a98b63(void);
extern swig_type_1 _wrap_Wrapped_GoRedSVD_matrixU_redsvd_578cfac526a98b63(uintptr_t arg1);
extern swig_type_2 _wrap_Wrapped_GoRedSVD_matrixUNotNormalized_redsvd_578cfac526a98b63(uintptr_t arg1);
extern swig_type_3 _wrap_Wrapped_GoRedSVD_singularValues_redsvd_578cfac526a98b63(uintptr_t arg1);
extern swig_type_4 _wrap_Wrapped_GoRedSVD_matrixV_redsvd_578cfac526a98b63(uintptr_t arg1);
extern swig_type_5 _wrap_Wrapped_GoRedSVD_matrixVNotNormalized_redsvd_578cfac526a98b63(uintptr_t arg1);
extern void _wrap_Wrapped_GoRedSVD_setUnnormalized_redsvd_578cfac526a98b63(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_Wrapped_GoRedSVD_redSVD__SWIG_0_redsvd_578cfac526a98b63(uintptr_t arg1);
extern _Bool _wrap_Wrapped_GoRedSVD_redSVD__SWIG_1_redsvd_578cfac526a98b63(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_Wrapped_GoRedSVD_setDenseMatrix32_redsvd_578cfac526a98b63(uintptr_t arg1, swig_type_6 arg2);
extern void _wrap_Wrapped_GoRedSVD_initializeSparseMatrix_redsvd_578cfac526a98b63(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3);
extern void _wrap_Wrapped_GoRedSVD_finalizeSparseMatrix_redsvd_578cfac526a98b63(uintptr_t arg1);
extern _Bool _wrap_Wrapped_GoRedSVD_addSparseMatrixRow_redsvd_578cfac526a98b63(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3, swig_type_7 arg4);
extern swig_type_8 _wrap_Wrapped_GoRedSVD_getColumnNorms_redsvd_578cfac526a98b63(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_redsvd_578cfac526a98b63(C.swig_intgo(_swig_i_0)))
	return swig_r
}



type GoRedSVD interface {
    Wrapped_GoRedSVD
    SetMatrix32(int, int, map[int]map[int]float32) bool
    SetMatrix64(int, int, map[int]map[int]float64) bool
}

func (arg SwigcptrWrapped_GoRedSVD) SetMatrix32(rows int, cols int, matrix map[int]map[int]float32) bool {
  arg.InitializeSparseMatrix(rows, cols)
  for k, _ := range matrix {
    matrixRow := make([]float32, cols)
    for i := 0; i < cols; i++ {
	matrixRow[i] = matrix[k][i]
    }
    arg.AddSparseMatrixRow(k, cols, matrixRow)
  }
  arg.FinalizeSparseMatrix()
  return true
}

 
func (arg SwigcptrWrapped_GoRedSVD) SetMatrix64(rows int, cols int, matrix map[int]map[int]float64) bool {
  arg.InitializeSparseMatrix(rows, cols)
  for k, _ := range matrix {
    matrixRow := make([]float32, cols)
    for i := 0; i < cols; i++ {
	matrixRow[i] = float32(matrix[k][i])
    }
    arg.AddSparseMatrixRow(k, cols, matrixRow)
  }
  arg.FinalizeSparseMatrix()
  return true
}

func DeleteGoRedSVD(arg1 GoRedSVD) {
  DeleteWrapped_GoRedSVD(arg1)
}
 
func NewGoRedSVD() (GoRedSVD) {
  svd := NewWrapped_GoRedSVD()
  return svd.(GoRedSVD)
}
 

type SwigcptrWrapped_GoRedSVD uintptr

func (p SwigcptrWrapped_GoRedSVD) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrWrapped_GoRedSVD) SwigIsWrapped_GoRedSVD() {
}

func DeleteWrapped_GoRedSVD(arg1 Wrapped_GoRedSVD) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Wrapped_GoRedSVD_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0))
}

func NewWrapped_GoRedSVD() (_swig_ret Wrapped_GoRedSVD) {
	var swig_r Wrapped_GoRedSVD
	swig_r = (Wrapped_GoRedSVD)(SwigcptrWrapped_GoRedSVD(C._wrap_new_Wrapped_GoRedSVD_redsvd_578cfac526a98b63()))
	return swig_r
}

func (arg1 SwigcptrWrapped_GoRedSVD) MatrixU() (_swig_ret [][]float32) {
	var swig_r [][]float32
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Wrapped_GoRedSVD_matrixU_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0))
	swig_r = *(*[][]float32)(unsafe.Pointer(&swig_r_p))
	return swig_r
}

func (arg1 SwigcptrWrapped_GoRedSVD) MatrixUNotNormalized() (_swig_ret [][]float32) {
	var swig_r [][]float32
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Wrapped_GoRedSVD_matrixUNotNormalized_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0))
	swig_r = *(*[][]float32)(unsafe.Pointer(&swig_r_p))
	return swig_r
}

func (arg1 SwigcptrWrapped_GoRedSVD) SingularValues() (_swig_ret []float32) {
	var swig_r []float32
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Wrapped_GoRedSVD_singularValues_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0))
	swig_r = *(*[]float32)(unsafe.Pointer(&swig_r_p))
	return swig_r
}

func (arg1 SwigcptrWrapped_GoRedSVD) MatrixV() (_swig_ret [][]float32) {
	var swig_r [][]float32
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Wrapped_GoRedSVD_matrixV_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0))
	swig_r = *(*[][]float32)(unsafe.Pointer(&swig_r_p))
	return swig_r
}

func (arg1 SwigcptrWrapped_GoRedSVD) MatrixVNotNormalized() (_swig_ret [][]float32) {
	var swig_r [][]float32
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Wrapped_GoRedSVD_matrixVNotNormalized_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0))
	swig_r = *(*[][]float32)(unsafe.Pointer(&swig_r_p))
	return swig_r
}

func (arg1 SwigcptrWrapped_GoRedSVD) SetUnnormalized(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Wrapped_GoRedSVD_setUnnormalized_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrWrapped_GoRedSVD) RedSVD__SWIG_0() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Wrapped_GoRedSVD_redSVD__SWIG_0_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrWrapped_GoRedSVD) RedSVD__SWIG_1(arg2 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(C._wrap_Wrapped_GoRedSVD_redSVD__SWIG_1_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (p SwigcptrWrapped_GoRedSVD) RedSVD(a ...interface{}) bool {
	argc := len(a)
	if argc == 0 {
		return p.RedSVD__SWIG_0()
	}
	if argc == 1 {
		return p.RedSVD__SWIG_1(a[0].(int))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrWrapped_GoRedSVD) SetDenseMatrix32(arg2 [][]float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Wrapped_GoRedSVD_setDenseMatrix32_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrWrapped_GoRedSVD) InitializeSparseMatrix(arg2 int, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Wrapped_GoRedSVD_initializeSparseMatrix_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func (arg1 SwigcptrWrapped_GoRedSVD) FinalizeSparseMatrix() {
	_swig_i_0 := arg1
	C._wrap_Wrapped_GoRedSVD_finalizeSparseMatrix_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrWrapped_GoRedSVD) AddSparseMatrixRow(arg2 int, arg3 int, arg4 []float32) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (bool)(C._wrap_Wrapped_GoRedSVD_addSparseMatrixRow_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func (arg1 SwigcptrWrapped_GoRedSVD) GetColumnNorms() (_swig_ret []float32) {
	var swig_r []float32
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Wrapped_GoRedSVD_getColumnNorms_redsvd_578cfac526a98b63(C.uintptr_t(_swig_i_0))
	swig_r = *(*[]float32)(unsafe.Pointer(&swig_r_p))
	return swig_r
}

type Wrapped_GoRedSVD interface {
	Swigcptr() uintptr
	SwigIsWrapped_GoRedSVD()
	MatrixU() (_swig_ret [][]float32)
	MatrixUNotNormalized() (_swig_ret [][]float32)
	SingularValues() (_swig_ret []float32)
	MatrixV() (_swig_ret [][]float32)
	MatrixVNotNormalized() (_swig_ret [][]float32)
	SetUnnormalized(arg2 bool)
	RedSVD(a ...interface{}) bool
	SetDenseMatrix32(arg2 [][]float32)
	InitializeSparseMatrix(arg2 int, arg3 int)
	FinalizeSparseMatrix()
	AddSparseMatrixRow(arg2 int, arg3 int, arg4 []float32) (_swig_ret bool)
	GetColumnNorms() (_swig_ret []float32)
}


